# RGLAB 386.4.4

In [1]:
import pandas as pd 
import numpy as np

In [4]:
data = {
    'Category': ['A', 'A', 'B', 'B', 'A', 'B'],
    'Value': [10, 15, 20, 25, 30, 35],
    'Fee' :[20000,25000,26000,22000,24000,35000],
    'Duration':['30day','40days','35days','40days','60days','60days'],
    'Discount':[1000,2300,1200,2500,2000,2000]
}

df = pd.DataFrame(data)

In [19]:
df.head(6)

  Category  Value    Fee Duration  Discount
0        A     10  20000    30day      1000
1        A     15  25000   40days      2300
2        B     20  26000   35days      1200
3        B     25  22000   40days      2500
4        A     30  24000   60days      2000
5        B     35  35000   60days      2000

In [20]:
# apply single aggregate func
total_sum = df['Value'].aggregate('sum')
print('Total sum:', total_sum)

Total sum: 135

In [16]:
sum2 = df['Value'].sum()
print('Totalsum2:', sum2)

Totalsum2: 135

In [17]:
# cumsum() running total
df[['Value']].cumsum()

   Value
0     10
1     25
2     45
3     70
4    100
5    135

In [25]:
# mean/avg
t_mean = df['Value'].agg('mean')
print('Avg mean:', t_mean)

#alternative
mean = df['Value'].mean()
print(f'Mean: {mean}')

Avg mean: 22.5
Mean: 22.5

In [27]:
max_v = df['Value'].agg('max')
print('Max Value:', max_v)

Max Value: 35

In [31]:
dev = df['Value'].agg('count')
print('Count:', dev)

count = df['Value'].count()
print('Count',count)

Count: 6
Count 6

In [34]:
std = df['Value'].agg('std')
print('STd:', std)

std1 = df['Value'].std()
print('STD1:', std1)

STd: 9.354143466934854
STD1: 9.354143466934854

In [36]:
result = df[['Fee', 'Discount']].agg('sum')

result

Fee         152000
Discount     11000
dtype: int64

In [41]:
# determine the total of each group an agg func

result_g = df.groupby('Category')[['Fee', 'Discount']].agg('sum')
result_g

            Fee  Discount
Category
A         69000      5300
B         83000      5700